<a href="https://colab.research.google.com/github/yaswanth-tech/my-resume/blob/main/da_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#day 1 11-08
def isPrime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

In [2]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd
print("pandas imported")

pandas imported

In [4]:
#creating series
import pandas as pd

data = [1,2,3,4]

s = pd.Series(data)

print(s)

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
data = [1,2,3,4,5]
i = ['a','b','c','d','e']
s=pd.Series(data, index = i)
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [6]:
#crearing series from dictionary
dict = pd.Series({'yash':25,'raj':7,'yaswanth':1275})
print(dict)

yash          25
raj            7
yaswanth    1275
dtype: int64

In [7]:
#accessing elements
print(s[:2])
print(s[0:2])
print(s[1:])
print(s[:2])

a    1
b    2
dtype: int64
a    1
b    2
dtype: int64
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
dtype: int64

In [8]:
#position based index
print(s[2])
print(s[4])
print(s[0])

3
5
1

/tmp/ipykernel_477/4029817636.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[2])
/tmp/ipykernel_477/4029817636.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[4])
/tmp/ipykernel_477/4029817636.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

In [9]:
data = [1,2,3,4,5]
i = ['a','b','c','d','e']
s=pd.Series(data, index = i)
print(s)
#updating
s['a'] = 7
print(s)
s['e'] = 77
print(s)
#inserting new data(directly, concat)
s['m'] = 777
print(s)
#remove(drop method)
s = s.drop('c')
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    7
b    2
c    3
d    4
e    5
dtype: int64
a     7
b     2
c     3
d     4
e    77
dtype: int64
a      7
b      2
c      3
d      4
e     77
m    777
dtype: int64
a      7
b      2
d      4
e     77
m    777
dtype: int64

In [10]:
Student_ID = [101,102,103,104,105]
Marks = [78,85,92,67,88]
ma = pd.Series(Marks, index = Student_ID)
print(ma)
print(ma[103])
ma[104] = 75
print(ma)
ma = ma.drop(102)
print(ma)
ma[106] = 90
print(ma)

101    78
102    85
103    92
104    67
105    88
dtype: int64
92
101    78
102    85
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
106    90
dtype: int64

In [11]:
Employee_ID = [1001 , 1002, 1003, 1004, 1005]
Salary = [35000, 42000, 38000, 50000, 45000]
sa = pd.Series(Salary, index = Employee_ID)
print(sa)
sa[1003]=40000
print(sa)
sa = sa.drop(1002)
print(sa)
sa[1006] = 55000
print(sa)
print(sa[:3])

1001    35000
1002    42000
1003    38000
1004    50000
1005    45000
dtype: int64
1001    35000
1002    42000
1003    40000
1004    50000
1005    45000
dtype: int64
1001    35000
1003    40000
1004    50000
1005    45000
dtype: int64
1001    35000
1003    40000
1004    50000
1005    45000
1006    55000
dtype: int64
1001    35000
1003    40000
1004    50000
dtype: int64

In [12]:
Product_Id = ['p101', 'p102', 'p103', 'p104', 'p105']
price = [500, 750, 1200, 900, 1500]
pr = pd.Series(price, index = Product_Id)
print(pr)
print(pr['p103'])
pr['p102'] = 800
print(pr)
pr = pr.drop('p104')
print(pr)
pr['p106'] = 2000
print(pr)

p101     500
p102     750
p103    1200
p104     900
p105    1500
dtype: int64
1200
p101     500
p102     800
p103    1200
p104     900
p105    1500
dtype: int64
p101     500
p102     800
p103    1200
p105    1500
dtype: int64
p101     500
p102     800
p103    1200
p105    1500
p106    2000
dtype: int64

In [13]:
Week = ['monday','tuesday','wednesday','thursday','friday','saturday','sunday']
temp = [31, 32, 34, 33,35,36, 34]
tp = pd.Series(temp, index = Week)
print(tp)
print(tp[:3])
tp['thursday'] = 32
print(tp)
tp = tp.drop('saturday')
print(tp)
tp['monday_next'] = 30
print(tp)

monday       31
tuesday      32
wednesday    34
thursday     33
friday       35
saturday     36
sunday       34
dtype: int64
monday       31
tuesday      32
wednesday    34
dtype: int64
monday       31
tuesday      32
wednesday    34
thursday     32
friday       35
saturday     36
sunday       34
dtype: int64
monday       31
tuesday      32
wednesday    34
thursday     32
friday       35
sunday       34
dtype: int64
monday         31
tuesday        32
wednesday      34
thursday       32
friday         35
sunday         34
monday_next    30
dtype: int64

In [14]:
#day-2 12-08
#view
s = pd.Series (
    [7700, 7000, 77, 7, 777],
    index = ['monday','tuesday','wednesday','thursday','friday']

)
print(s)
print(s.head(3))  #takes from top
print(s.tail(2))  #takes from bottom
print(len(s))     #length
print(s.shape)    #rows and columns
print(s.index)    #all indexs
print(s.values)   #all values

monday       7700
tuesday      7000
wednesday      77
thursday        7
friday        777
dtype: int64
monday       7700
tuesday      7000
wednesday      77
dtype: int64
thursday      7
friday      777
dtype: int64
5
(5,)
Index(['monday', 'tuesday', 'wednesday', 'thursday', 'friday'], dtype='object')
[7700 7000   77    7  777]

In [15]:
#selecting and filtering
s['monday']               #specific index
s[['monday','wednesday']] #multiple index, nested list
s > 6000                  #filtering using a condition, gives boolen condition, true or false
s[s>6000]                 #filtering, gives only the values satisfying the condition

monday     7700
tuesday    7000
dtype: int64

In [16]:
'''cleaning data
1)missing values-Nan-not a number
'''
s = pd.Series([77,7000,None,777,None])
print(s)
print(s.isna())       # returns the boolean value, returns true if nan, return false if value
print(s.isna().sum()) # count of missing values
print(s.fillna(0))    # fill the value u want to replace
print(s.dropna())     # drop the missing values

#manipulating
s=s.replace(5000, 5500)
print(s)

0      77.0
1    7000.0
2       NaN
3     777.0
4       NaN
dtype: float64
0    False
1    False
2     True
3    False
4     True
dtype: bool
2
0      77.0
1    7000.0
2       0.0
3     777.0
4       0.0
dtype: float64
0      77.0
1    7000.0
3     777.0
dtype: float64
0      77.0
1    7000.0
2       NaN
3     777.0
4       NaN
dtype: float64

In [17]:
# creating DataFrame with list

import pandas as pd

data = [
    ['yaswanth', 21, 77000],
    ['rajana', 27, 7000],
    ['yashraj', 77, 700]
]

df = pd.DataFrame(data)

print(df)

          0   1      2
0  yaswanth  21  77000
1    rajana  27   7000
2   yashraj  77    700

In [18]:
# creating Dataframe with tuple

import pandas as pd

data = [
    ('yaswanth', 21, 77000),
    ('rajana', 27, 7000),
    ('yashraj', 77, 700)
]

df = pd.DataFrame(data)

print(df)

          0   1      2
0  yaswanth  21  77000
1    rajana  27   7000
2   yashraj  77    700

In [19]:
#creating dataframe using set
import pandas as pd

my_set = (7, 77, 777, 7777)

df_from_set = pd.DataFrame(
    list(my_set),
    columns = ['values']
)

print(df_from_set)

   values
0       7
1      77
2     777
3    7777

In [20]:
# creating dataframe using dictionary
import pandas as pd

data = {
    'Name': ['yash', 'yaswanth', 'yashraj'],
    'age': [21, 7, 77],
    'city': ['vizag', 'ranchi', 'london']
}

df = pd.DataFrame(data)

print(df)

       Name  age    city
0      yash   21   vizag
1  yaswanth    7  ranchi
2   yashraj   77  london

In [21]:
#converting series into dataframe
s = pd.Series(
    [7,77,777],
    name='Numbers'
)

s2 = pd.Series(
    [1,2,3],
    name='num'
)

s3 = pd.Series(
    [4,5,6],
    name='num2'
)

df = pd.DataFrame({
    'Numbers': s,
    'num': s2,
    'num2': s3
})

print(df)

   Numbers  num  num2
0        7    1     4
1       77    2     5
2      777    3     6

In [22]:
#dataframe for 5 students with three subject marks
import pandas as pd

data = [
    ['Yaswanth', 85, 78, 90],
    ['Rahul', 75, 82, 88],
    ['Priya', 92, 89, 95],
    ['Arjun', 68, 74, 80],
    ['Sneha', 88, 91, 86]
]

df = pd.DataFrame(data, columns=['Name', 'Python', 'Maths', 'English'])

print(df)

       Name  Python  Maths  English
0  Yaswanth      85     78       90
1     Rahul      75     82       88
2     Priya      92     89       95
3     Arjun      68     74       80
4     Sneha      88     91       86

In [23]:
#dataframe for sales, profit and loss
import pandas as pd

data = [
    ('Monday', 10000, 2000, 500),
    ('Tuesday', 12000, 2500, 400),
    ('Wednesday', 9000, 1800, 700),
    ('Thursday', 15000, 3000, 300),
    ('Friday', 11000, 2200, 600),
    ('Saturday', 18000, 4000, 200),
    ('Sunday', 14000, 2800, 500)
]

df = pd.DataFrame(data, columns=['Day', 'Sales', 'Profit', 'Loss'])

print(df)

         Day  Sales  Profit  Loss
0     Monday  10000    2000   500
1    Tuesday  12000    2500   400
2  Wednesday   9000    1800   700
3   Thursday  15000    3000   300
4     Friday  11000    2200   600
5   Saturday  18000    4000   200
6     Sunday  14000    2800   500

In [24]:
#dataframe using dictionary
import pandas as pd

data = {
    'Name': ['Yaswanth', 'Rahul', 'Priya', 'Arjun', 'Sneha'],
    'Age': [21, 22, 20, 21, 22],
    'City': ['Vizag', 'Hyderabad', 'Vijayawada', 'Chennai', 'Bangalore']
}

df = pd.DataFrame(data)

print(df)

       Name  Age        City
0  Yaswanth   21       Vizag
1     Rahul   22   Hyderabad
2     Priya   20  Vijayawada
3     Arjun   21     Chennai
4     Sneha   22   Bangalore

In [25]:
#day-3, 17-08
#loc
import pandas as pd

s = pd.Series (
    [7700, 7000, 77, 7, 777],
    index = ['monday','tuesday','wednesday','thursday','friday']

)
print(s)

print(s.iloc[0]) #passing integer within range - iloc
print(s.iloc[0:3])
print(s.loc['monday']) #passing only user defined index - loc

monday       7700
tuesday      7000
wednesday      77
thursday        7
friday        777
dtype: int64
7700
monday       7700
tuesday      7000
wednesday      77
dtype: int64
7700

In [26]:
import pandas as pd
data = {
    'name':['yaswanth','lakshman','nandan','varun','sami'],
    'age':[21,22,None,23,24],
    'city':['vizag','hyderabad','delhi',None, 'bengaluru'],
    'salary':[77700,7700,7777,777,None]
}

i = [71, 72, 73, 74, 75]

df = pd.DataFrame(data, index = i)
print(df)
print(df.iloc[0:2]) #it will include only starting value
print(df.loc[73])
df.loc[71:74] # it will include the starting and ending values also

        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
73    nandan   NaN      delhi   7777.0
74     varun  23.0       None    777.0
75      sami  24.0  bengaluru      NaN
        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
name      nandan
age          NaN
city       delhi
salary    7777.0
Name: 73, dtype: object

        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
73    nandan   NaN      delhi   7777.0
74     varun  23.0       None    777.0

In [27]:
#aggregation
s = pd.Series (
    [7700, 7000, 77, 7, 777],
    index = ['monday','tuesday','wednesday','thursday','friday']

)
print(s)
print(s.min())
print(s.max())
print(s.count())
print(s.mean())
print(s.median())
print(s.std())  #standard deviation
print(s.sum())

monday       7700
tuesday      7000
wednesday      77
thursday        7
friday        777
dtype: int64
7
7700
5
3112.2
777.0
3888.1474637672886
15561

In [28]:
data = {
    'name':['yaswanth','lakshman','nandan','varun','sami'],
    'age':[21,22,None,23,24],
    'city':['vizag','hyderabad','delhi',None, 'bengaluru'],
    'salary':[77700,7700,7777,777,None]
}

i = [71, 72, 73, 74, 75]

df = pd.DataFrame(data, index = i)
print(df)
print(df.min)
print(df.max)
print(df.count)
print(df.mean)
print(df.median)
print(df.std)

        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
73    nandan   NaN      delhi   7777.0
74     varun  23.0       None    777.0
75      sami  24.0  bengaluru      NaN
<bound method DataFrame.min of         name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
73    nandan   NaN      delhi   7777.0
74     varun  23.0       None    777.0
75      sami  24.0  bengaluru      NaN>
<bound method DataFrame.max of         name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
73    nandan   NaN      delhi   7777.0
74     varun  23.0       None    777.0
75      sami  24.0  bengaluru      NaN>
<bound method DataFrame.count of         name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
73    nandan   NaN      delhi   7777.0
74     varun  23.0       None    777.0
75      sami  24.0  bengaluru      NaN>
<bound method DataFrame.mean of         name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
73    nandan   NaN      delhi   7777.0
74     varun  23.0       None    777.0
75      sami  24.0  bengaluru      NaN>
<bound method DataFrame.median of         name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
73    nandan   NaN      delhi   7777.0
74     varun  23.0       None    777.0
75      sami  24.0  bengaluru      NaN>
<bound method DataFrame.std of         name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
73    nandan   NaN      delhi   7777.0
74     varun  23.0       None    777.0
75      sami  24.0  bengaluru      NaN>

In [29]:
#concat(add) multiple series
s1 = pd.Series([7,77,777])
s2 = pd.Series([1,11,111])

result = pd.concat([s1,s2], ignore_index=True) #ignore_index= True, we will reaarange the index while combining series
print(result)

0      7
1     77
2    777
3      1
4     11
5    111
dtype: int64

In [30]:
sales = [25000, 30000, 35000, 40000, None, 45000, 50000, None, 10000, 15000 ]
i = ['01-aug','02-aug','03-aug','04-aug','05-aug','06-aug','07-aug','08-aug','09-aug','10-aug']
s = pd.Series(sales, index = i)
print(s)
print(s.head(5))
print(s.tail(3))
print(s.isna())
print(s.isna().sum())
print(s.fillna(s.mean()))
print(s[s > 35000])
s['03-aug'] = 34000
print(s)
s= s.drop('04-aug')
print(s)
s['11-aug'] = 50000
print(s)
print(s.sum())
print(s.mean())
print(s.max())
print(s.min())

01-aug    25000.0
02-aug    30000.0
03-aug    35000.0
04-aug    40000.0
05-aug        NaN
06-aug    45000.0
07-aug    50000.0
08-aug        NaN
09-aug    10000.0
10-aug    15000.0
dtype: float64
01-aug    25000.0
02-aug    30000.0
03-aug    35000.0
04-aug    40000.0
05-aug        NaN
dtype: float64
08-aug        NaN
09-aug    10000.0
10-aug    15000.0
dtype: float64
01-aug    False
02-aug    False
03-aug    False
04-aug    False
05-aug     True
06-aug    False
07-aug    False
08-aug     True
09-aug    False
10-aug    False
dtype: bool
2
01-aug    25000.0
02-aug    30000.0
03-aug    35000.0
04-aug    40000.0
05-aug    31250.0
06-aug    45000.0
07-aug    50000.0
08-aug    31250.0
09-aug    10000.0
10-aug    15000.0
dtype: float64
04-aug    40000.0
06-aug    45000.0
07-aug    50000.0
dtype: float64
01-aug    25000.0
02-aug    30000.0
03-aug    34000.0
04-aug    40000.0
05-aug        NaN
06-aug    45000.0
07-aug    50000.0
08-aug        NaN
09-aug    10000.0
10-aug    15000.0
dtype: float64
01-aug    25000.0
02-aug    30000.0
03-aug    34000.0
05-aug        NaN
06-aug    45000.0
07-aug    50000.0
08-aug        NaN
09-aug    10000.0
10-aug    15000.0
dtype: float64
01-aug    25000.0
02-aug    30000.0
03-aug    34000.0
05-aug        NaN
06-aug    45000.0
07-aug    50000.0
08-aug        NaN
09-aug    10000.0
10-aug    15000.0
11-aug    50000.0
dtype: float64
259000.0
32375.0
50000.0
10000.0

In [31]:
r = [120000, 130000, None, 140000, 150000, None, 160000, 170000, 180000, 190000]
i = ['january','feburary','march','april','may','june','july','august','september','october']

s = pd.Series(r, index = i)
print(s)
print(s.head(5))
print(s.tail(3))
print(s.loc[['january','march','may']])
print(s[s>170000])
print(s.isna())
print(s.isna().sum())
print(s.fillna(s.mean()))
s['april'] = 155000
print(s)
s = s.drop('feburary')
print(s)
s['november'] = 240000
print(s)
print(s.sum())
print(s.mean())
print(s.max())
print(s.min())

january      120000.0
feburary     130000.0
march             NaN
april        140000.0
may          150000.0
june              NaN
july         160000.0
august       170000.0
september    180000.0
october      190000.0
dtype: float64
january     120000.0
feburary    130000.0
march            NaN
april       140000.0
may         150000.0
dtype: float64
august       170000.0
september    180000.0
october      190000.0
dtype: float64
january    120000.0
march           NaN
may        150000.0
dtype: float64
september    180000.0
october      190000.0
dtype: float64
january      False
feburary     False
march         True
april        False
may          False
june          True
july         False
august       False
september    False
october      False
dtype: bool
2
january      120000.0
feburary     130000.0
march        155000.0
april        140000.0
may          150000.0
june         155000.0
july         160000.0
august       170000.0
september    180000.0
october      190000.0
dtype: float64
january      120000.0
feburary     130000.0
march             NaN
april        155000.0
may          150000.0
june              NaN
july         160000.0
august       170000.0
september    180000.0
october      190000.0
dtype: float64
january      120000.0
march             NaN
april        155000.0
may          150000.0
june              NaN
july         160000.0
august       170000.0
september    180000.0
october      190000.0
dtype: float64
january      120000.0
march             NaN
april        155000.0
may          150000.0
june              NaN
july         160000.0
august       170000.0
september    180000.0
october      190000.0
november     240000.0
dtype: float64
1365000.0
170625.0
240000.0
120000.0

In [32]:
#day-4 19-08
import pandas as pd
s = pd.Series(
    [1,2,3,4],
    name = 'numbers'
)
s2 = pd.Series([9,8,7,6])
s3 = pd.Series([11,12,13,14])

df = s.to_frame()        #for one series into dataframe
d = {
    "num1":s,
    "num2":s2,
    "num3":s3
}
df = pd.DataFrame(d)     #for multiple series into dataframe we use dictonary
print(df)
#renaming multiple columns
df.rename(
    columns = {
        'num1' : 'numbers1',
        'num2' : 'numbers2'
    },
    inplace=True
)
print(df)

#renaming single column
s = pd.Series(
    [1,2,3,4],
    name = 'numbers'
)
df = s.to_frame()
print(df)
df.columns = ['digits']
print(df)

   num1  num2  num3
0     1     9    11
1     2     8    12
2     3     7    13
3     4     6    14
   numbers1  numbers2  num3
0         1         9    11
1         2         8    12
2         3         7    13
3         4         6    14
   numbers
0        1
1        2
2        3
3        4
   digits
0       1
1       2
2       3
3       4

In [33]:
#viewing in dataframe
data = {
    'name':['yaswanth','lakshman','nandan','varun','sami'],
    'age':[21,22,None,23,24],
    'city':['vizag','hyderabad','delhi',None, 'bengaluru'],
    'salary':[77700,7700,7777,777,None]
}

i = [71, 72, 73, 74, 75]

df = pd.DataFrame(data, index = i)
print(df)
print(df.head(2))
print(df.tail(3))
print(df.shape)
print(df.count())
print(df.index)
print(df.values)
print(df.info())     #gives physical or structural information
print(df.describe()) #gives mahematical or statistical information

#selecting in dataframe
print(df['city'])            #for one column
print(df[['name','age']])    #for multiple columns
names = df['name']
print(names)
print(df.iloc[0])            #gives the particular row using index
print(df.iloc[0:3])          #gives multiple rows but not the end value
print(df.loc[71])            #gives particular row based on index values user-defined
print(df.loc[71:73])         #gives multiple rows including the end value

        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
73    nandan   NaN      delhi   7777.0
74     varun  23.0       None    777.0
75      sami  24.0  bengaluru      NaN
        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
      name   age       city  salary
73  nandan   NaN      delhi  7777.0
74   varun  23.0       None   777.0
75    sami  24.0  bengaluru     NaN
(5, 4)
name      5
age       4
city      4
salary    4
dtype: int64
Index([71, 72, 73, 74, 75], dtype='int64')
[['yaswanth' 21.0 'vizag' 77700.0]
 ['lakshman' 22.0 'hyderabad' 7700.0]
 ['nandan' nan 'delhi' 7777.0]
 ['varun' 23.0 None 777.0]
 ['sami' 24.0 'bengaluru' nan]]
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 71 to 75
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     4 non-null      float64
 2   city    4 non-null      object
 3   salary  4 non-null      float64
dtypes: float64(2), object(2)
memory usage: 200.0+ bytes
None
             age        salary
count   4.000000      4.000000
mean   22.500000  23488.500000
std     1.290994  36289.699774
min    21.000000    777.000000
25%    21.750000   5969.250000
50%    22.500000   7738.500000
75%    23.250000  25257.750000
max    24.000000  77700.000000
71        vizag
72    hyderabad
73        delhi
74         None
75    bengaluru
Name: city, dtype: object
        name   age
71  yaswanth  21.0
72  lakshman  22.0
73    nandan   NaN
74     varun  23.0
75      sami  24.0
71    yaswanth
72    lakshman
73      nandan
74       varun
75        sami
Name: name, dtype: object
name      yaswanth
age           21.0
city         vizag
salary     77700.0
Name: 71, dtype: object
        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
73    nandan   NaN      delhi   7777.0
name      yaswanth
age           21.0
city         vizag
salary     77700.0
Name: 71, dtype: object
        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  22.0  hyderabad   7700.0
73    nandan   NaN      delhi   7777.0

In [45]:
#filtering in df
data = {
    'name':['yaswanth','lakshman','nandan','varun','sami'],
    'age':[21,25,None,23,24],
    'city':['vizag','hyderabad','bombay',None, 'bengaluru'],
    'salary':[77700,7700,7777,777,None]
}

i = [71, 72, 73, 74, 75]

df = pd.DataFrame(data, index = i)
print(df)
print("-------------------------")
print(df[df['age']>21])  #df[df] gives values of particular condition, wheres as df will give boolean values
print("-------------------------")
print(df[df['salary']>40000])
print("-------------------------")
print(df[df['city']=='hyderabad'])
print("-------------------------")
print(df[(df['age'] > 22) & (df['city'] == 'hyderabad')])
print("-------------------------")
print(df[(df['city']=='bombay') | (df['salary'] > 25000)])
print("-------------------------")
print(df.isna())       # returns the boolean value, returns true if nan, return false if value
print("-------------------------")
print(df.isna().sum()) # count of missing values
print("-------------------------")
print(df.fillna(0))    # fill the value u want to replace
print("-------------------------")
print(df.dropna())     # drop the missing values
print("-------------------------")
print(df.dropna(axis=1))  #removing columns missing values
print("-------------------------")
print(df.dropna(axis=0))
print("-------------------------")
print(df.dropna(how='all'))
print("-------------------------")
print(df.dropna(inplace=True))
print("-------------------------")
print(df.fillna(0))
print("-------------------------")
b = df.fillna({              #filling different columns with different values
    'age': 0,
    'city': 'Unknown'
})
print(b)
print("-------------------------")
df['age'] = df['age'].fillna(df['age'].mean())  #fill numerical missing values with mean

        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  25.0  hyderabad   7700.0
73    nandan   NaN     bombay   7777.0
74     varun  23.0       None    777.0
75      sami  24.0  bengaluru      NaN
-------------------------
        name   age       city  salary
72  lakshman  25.0  hyderabad  7700.0
74     varun  23.0       None   777.0
75      sami  24.0  bengaluru     NaN
-------------------------
        name   age   city   salary
71  yaswanth  21.0  vizag  77700.0
-------------------------
        name   age       city  salary
72  lakshman  25.0  hyderabad  7700.0
-------------------------
        name   age       city  salary
72  lakshman  25.0  hyderabad  7700.0
-------------------------
        name   age    city   salary
71  yaswanth  21.0   vizag  77700.0
73    nandan   NaN  bombay   7777.0
-------------------------
     name    age   city  salary
71  False  False  False   False
72  False  False  False   False
73  False   True  False   False
74  False  False   True   False
75  False  False  False    True
-------------------------
name      0
age       1
city      1
salary    1
dtype: int64
-------------------------
        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  25.0  hyderabad   7700.0
73    nandan   0.0     bombay   7777.0
74     varun  23.0          0    777.0
75      sami  24.0  bengaluru      0.0
-------------------------
        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  25.0  hyderabad   7700.0
-------------------------
        name
71  yaswanth
72  lakshman
73    nandan
74     varun
75      sami
-------------------------
        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  25.0  hyderabad   7700.0
-------------------------
        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  25.0  hyderabad   7700.0
73    nandan   NaN     bombay   7777.0
74     varun  23.0       None    777.0
75      sami  24.0  bengaluru      NaN
-------------------------
None
-------------------------
        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  25.0  hyderabad   7700.0
-------------------------
        name   age       city   salary
71  yaswanth  21.0      vizag  77700.0
72  lakshman  25.0  hyderabad   7700.0
-------------------------

In [61]:
#day-5 20-08
print(df.isna())       # returns the boolean value, returns true if nan, return false if value
print("-------------------------")
print(df.isna().sum()) # count of missing values
print("-------------------------")
print(df.fillna(0))    # fill the value u want to replace
print("-------------------------")
print(df.dropna())     # drop the missing values
print("-------------------------")
print(df.dropna(axis=1))  #removing columns missing values
print("-------------------------")
print(df.dropna(axis=0))   #removing rows
print("-------------------------")
print(df.dropna(how='all'))
print("-------------------------")
print(df.dropna(inplace=True))
print("-------------------------")
print(df.fillna(0))
print("-------------------------")
b = df.fillna({              #filling different columns with different values
    'age': 0,
    'city': 'Unknown'
},inplace=True)
print(b)
print("-------------------------")
df['age'] == df['age'].fillna(df['age'].mean())
print(df)  #fill numerical missing values with mean

   employee_id   city  experience    age  salary
0        False  False       False  False   False
1        False  False       False  False   False
2        False  False       False  False   False
3        False  False       False  False   False
4        False  False       False  False   False
-------------------------
employee_id    0
city           0
experience     0
age            0
salary         0
dtype: int64
-------------------------
   employee_id       city  experience   age  salary
0           71  hyderabad         0.0  25.0   77000
1           72    chennai         4.0  30.0   20000
2           73  bangalore         3.0  27.5    7777
3           74    Unknown         5.0  35.0   77770
4           71  hyderabad         2.0  25.0     777
-------------------------
   employee_id       city  experience   age  salary
0           71  hyderabad         0.0  25.0   77000
1           72    chennai         4.0  30.0   20000
2           73  bangalore         3.0  27.5    7777
3           74    Unknown         5.0  35.0   77770
4           71  hyderabad         2.0  25.0     777
-------------------------
   employee_id       city  experience   age  salary
0           71  hyderabad         0.0  25.0   77000
1           72    chennai         4.0  30.0   20000
2           73  bangalore         3.0  27.5    7777
3           74    Unknown         5.0  35.0   77770
4           71  hyderabad         2.0  25.0     777
-------------------------
   employee_id       city  experience   age  salary
0           71  hyderabad         0.0  25.0   77000
1           72    chennai         4.0  30.0   20000
2           73  bangalore         3.0  27.5    7777
3           74    Unknown         5.0  35.0   77770
4           71  hyderabad         2.0  25.0     777
-------------------------
   employee_id       city  experience   age  salary
0           71  hyderabad         0.0  25.0   77000
1           72    chennai         4.0  30.0   20000
2           73  bangalore         3.0  27.5    7777
3           74    Unknown         5.0  35.0   77770
4           71  hyderabad         2.0  25.0     777
-------------------------
None
-------------------------
   employee_id       city  experience   age  salary
0           71  hyderabad         0.0  25.0   77000
1           72    chennai         4.0  30.0   20000
2           73  bangalore         3.0  27.5    7777
3           74    Unknown         5.0  35.0   77770
4           71  hyderabad         2.0  25.0     777
-------------------------
None
-------------------------
   employee_id       city  experience   age  salary
0           71  hyderabad         0.0  25.0   77000
1           72    chennai         4.0  30.0   20000
2           73  bangalore         3.0  27.5    7777
3           74    Unknown         5.0  35.0   77770
4           71  hyderabad         2.0  25.0     777

In [72]:
emp_details = {
    'emp_id' :[71,72,73,74,71],
    'city' : ['hyderabad','chennai','bangalore',None,'hyderabad'],
    'experience' : [None, 4, 3, 5, 2],
    'age':[25,30, None, 35,25]

}
df=pd.DataFrame(emp_details)
print(df)
print("-------------------------")
print(df.isna())
print("-------------------------")
print(df.dropna())
print("-------------------------")
print(df.isna().sum())
print("-------------------------")
b = df.fillna({           #experience =0, city = unknown
    'experience': 0,
    'city': 'Unknown'
},inplace = True)
print(b)
df['age'] == df['age'].fillna(df['age'].median(), inplace = True)   #age=median
print(df)
print("-------------------------")
df.rename(columns={"emp_id":'employee_id'},inplace=True)   #replace emp_id as employee_id
#create new column as salary for all employees --- manipulating
df['salary'] = [77000, None, 7777, 77770, 777]
print(df)
print("-------------------------")
df['age'] = df['age'] + 1        #age + 1
print(df)
print("-------------------------")
df['bonus'] = df['salary'] / 10  #10% bonus to salary
print(df)
print("-------------------------")
df.drop('bonus', axis =1 , inplace = True)  #drop bonus column
print(df)
print("-------------------------")
#df.drop(columns=['age', 'salary'],inplace=True)-drop multiple columns
df.loc[len(df)] = [77, 'vizag', 7, 17, 77]
print(df)
print("-------------------------")
df.drop(2,axis = 0, inplace = True)   #dropping a specific row
print(df)
print("-------------------------")

   emp_id       city  experience   age
0      71  hyderabad         NaN  25.0
1      72    chennai         4.0  30.0
2      73  bangalore         3.0   NaN
3      74       None         5.0  35.0
4      71  hyderabad         2.0  25.0
-------------------------
   emp_id   city  experience    age
0   False  False        True  False
1   False  False       False  False
2   False  False       False   True
3   False   True       False  False
4   False  False       False  False
-------------------------
   emp_id       city  experience   age
1      72    chennai         4.0  30.0
4      71  hyderabad         2.0  25.0
-------------------------
emp_id        0
city          1
experience    1
age           1
dtype: int64
-------------------------
None
   emp_id       city  experience   age
0      71  hyderabad         0.0  25.0
1      72    chennai         4.0  30.0
2      73  bangalore         3.0  27.5
3      74    Unknown         5.0  35.0
4      71  hyderabad         2.0  25.0
-------------------------
   employee_id       city  experience   age   salary
0           71  hyderabad         0.0  25.0  77000.0
1           72    chennai         4.0  30.0      NaN
2           73  bangalore         3.0  27.5   7777.0
3           74    Unknown         5.0  35.0  77770.0
4           71  hyderabad         2.0  25.0    777.0
-------------------------
   employee_id       city  experience   age   salary
0           71  hyderabad         0.0  26.0  77000.0
1           72    chennai         4.0  31.0      NaN
2           73  bangalore         3.0  28.5   7777.0
3           74    Unknown         5.0  36.0  77770.0
4           71  hyderabad         2.0  26.0    777.0
-------------------------
   employee_id       city  experience   age   salary   bonus
0           71  hyderabad         0.0  26.0  77000.0  7700.0
1           72    chennai         4.0  31.0      NaN     NaN
2           73  bangalore         3.0  28.5   7777.0   777.7
3           74    Unknown         5.0  36.0  77770.0  7777.0
4           71  hyderabad         2.0  26.0    777.0    77.7
-------------------------
   employee_id       city  experience   age   salary
0           71  hyderabad         0.0  26.0  77000.0
1           72    chennai         4.0  31.0      NaN
2           73  bangalore         3.0  28.5   7777.0
3           74    Unknown         5.0  36.0  77770.0
4           71  hyderabad         2.0  26.0    777.0
-------------------------
   employee_id       city  experience   age   salary
0           71  hyderabad         0.0  26.0  77000.0
1           72    chennai         4.0  31.0      NaN
2           73  bangalore         3.0  28.5   7777.0
3           74    Unknown         5.0  36.0  77770.0
4           71  hyderabad         2.0  26.0    777.0
5           77      vizag         7.0  17.0     77.0
-------------------------
   employee_id       city  experience   age   salary
0           71  hyderabad         0.0  26.0  77000.0
1           72    chennai         4.0  31.0      NaN
3           74    Unknown         5.0  36.0  77770.0
4           71  hyderabad         2.0  26.0    777.0
5           77      vizag         7.0  17.0     77.0

In [74]:
emp_details = {
    'emp_id' :[71,72,73,74,71],
    'city' : ['hyderabad','chennai','bangalore',None,'hyderabad'],
    'experience' : [None, 4, 3, 5, 2],
    'age':[25,30, None, 35,25]

}
df=pd.DataFrame(emp_details)
print(df)
print("-------------------------")
print(df.groupby('city')['age'].mean())
print("-------------------------")
print(df.groupby('city')['age'].median())
print("-------------------------")
print(df.groupby('city')['age'].min())
print("-------------------------")
print(df.groupby('city')['age'].max())
print("-------------------------")
print(df.groupby('city')['age'].count())

   emp_id       city  experience   age
0      71  hyderabad         NaN  25.0
1      72    chennai         4.0  30.0
2      73  bangalore         3.0   NaN
3      74       None         5.0  35.0
4      71  hyderabad         2.0  25.0
-------------------------
city
bangalore     NaN
chennai      30.0
hyderabad    25.0
Name: age, dtype: float64
-------------------------
city
bangalore     NaN
chennai      30.0
hyderabad    25.0
Name: age, dtype: float64
-------------------------
city
bangalore     NaN
chennai      30.0
hyderabad    25.0
Name: age, dtype: float64
-------------------------
city
bangalore     NaN
chennai      30.0
hyderabad    25.0
Name: age, dtype: float64
-------------------------
city
bangalore    0
chennai      1
hyderabad    2
Name: age, dtype: int64